language: r
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get -y install r-cran-rjava
  - R CMD javareconf

cache: packages
warnings_are_errors: true
matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
r_github_packages: petermeissner/kafkaesquejars
r_packages:
  - covr
after_success:
  - R -q -e 'library("covr");codecov()'