name: Test

on: push

# on:
#   workflow_dispatch:
#   repository_dispatch:
#     types: ["manual_trigger"]

    
jobs:
  test_system_self_test:
    runs-on: ubuntu-latest
    services:
      kafkatest: 
        image: petermeissner/kafkatest
        ports: 
          - "2181:2181"
          - "9092:9092"
    steps:
      - name: Check if zookeeper is up and running
        run: |
          until echo "srvr" | nc localhost 2181 | grep Mode -c ; do echo "waiting"; sleep 1; done
          echo "waiting done"
          echo srvr | nc localhost 2181
          echo "sleeping some more"
          sleep 5 
          echo srvr | nc localhost 2181
          ls -la
